name = "MathrewDoggy Blog"
license = "MIT"
licenselink = "https://github.com/mathdoggy/blog/blob/main/LICENSE"
description = "HBstack Theme Template"
homepage = "https://github.com/mathdoggy/blog"
demosite = "https://mathdoggy.github.io/blog/"
tags = [
    "archive",
    "blog",
    "bootstrap",
    "dark",
    "dark mode",
    "docs",
    "gallery",
    "landing",
    "multilingual",
    "personal",
    "responsive"
]

features = ["search", "flexible", "modular"]

[author]
name = "Mathrew Doggy"
homepage = "https://mathdoggy.bearblog.dev/"
